# Generated by Django 3.1.4 on 2021-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210503_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='PhoneNo',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postalcode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
